/* CRIANDO UMA TABELA SQL
** VARCHAR SERVE PARA STRINGS COM POSIÇÃO SELECIONADAS
** FLOAT É UM SUBTIPO DE NUMBER*/  
CREATE TABLE TABELA_DE_VENDEDORES (
MATRICULA VARCHAR (5)PRIMARY KEY,
NOME VARCHAR (100),
PERCENTUAL_COMISSAO FLOAT);
/* CRIANDO SEGUNDA TABELA PARA APAGAR*/ 
CREATE TABLE TABELA_DE_VENDEDORES2 (
MATRICULA VARCHAR (5)PRIMARY KEY,
NOME VARCHAR (100),
PERCENTUAL_COMISSAO FLOAT);

DROP TABLE TABELA_DE_VENDEDORES2;

/* INSERIR VENDEDORES NA TABELA DE VENDEDORES*/
INSERT INTO tabela_de_vendedores(
MATRICULA, NOME, percentual_comissao) 
VALUES ('00233', 'José Geraldo da Fonseca', 0.1);

INSERT INTO tabela_de_vendedores(
MATRICULA, NOME, PERCENTUAL_COMISSAO) 
VALUES ('00235', 'Márcio Almeida Silva', 0.08);
INSERT INTO tabela_de_vendedores(
MATRICULA, NOME, PERCENTUAL_COMISSAO) 
VALUES ('00236', 'Cláudia Morais', 0.08);

/*ATUALIZAÇÃO DO REGISTRO
** A Claudia passsou a ter comissão de 11% 
** O José reclamou que seu nome é na verdade José Geraldo da Fonseca Júnior*/
UPDATE TABELA_DE_VENDEDORES SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00236';
UPDATE TABELA_DE_VENDEDORES SET NOME = 'José Geraldo da Fonseca Júnior'
WHERE MATRICULA = '00235';

/*Cometi um erro na atualização do vendedor, vou arrumar. O José não tem essa matricula*/
UPDATE TABELA_DE_VENDEDORES SET NOME = 'José Geraldo da Fonseca Júnior'
WHERE MATRICULA = '00233';
UPDATE TABELA_DE_VENDEDORES SET NOME = 'Márcio Almeida Silva'
WHERE MATRICULA = '00235';


/*Vamos apagar e alterar toda a tabela */
DROP TABLE TABELA_DE_VENDEDORES;
CREATE TABLE TABELA_DE_VENDEDORES (
     MATRICULA VARCHAR(5),
     NOME VARCHAR(100),
     PERCENTUAL_COMISSAO FLOAT,
     DATA_ADMISSAO DATE,
     DE_FERIAS NUMBER(1)
);
ALTER TABLE TABELA_DE_VENDEDORES ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY (MATRICULA);
INSERT INTO TABELA_DE_VENDEDORES (
     MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS
) VALUES (
     '00235','Márcio Almeida Silva',0.08,TO_DATE('15/08/2014','DD/MM/YYYY'),0
);
INSERT INTO TABELA_DE_VENDEDORES (
     MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO,DE_FERIAS
) VALUES (
     '00236','Cláudia Morais',0.08,TO_DATE('17/09/2013','DD/MM/YYYY'),1
);
INSERT INTO TABELA_DE_VENDEDORES (
     MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO,DE_FERIAS
) VALUES (
     '00237','Roberta Martins',0.11,TO_DATE('18/03/2017','DD/MM/YYYY'),1
);
INSERT INTO TABELA_DE_VENDEDORES (
     MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO,DE_FERIAS
) VALUES (
     '00238','Péricles Alves',0.11,TO_DATE('21/08/2016','DD/MM/YYYY'),0
);


/*Como fazer seleções na tabela?*/
SELECT NOME, MATRICULA FROM tabela_de_vendedores;

SELECT * FROM tabela_de_vendedores;

SELECT * FROM TABELA_DE_VENDEDORES WHERE de_ferias = 1;

/*Como está a vendedora Cláudia Morais?*/
SELECT * FROM TABELA_DE_VENDEDORES WHERE NOME = 'Cláudia Morais';

/*Obtendo valores de comissão maior que 10%*/
SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

/*Quais vendedores foram admitidos 2016 adiante na loja?*/
SELECT * FROM TABELA_DE_VENDEDORES WHERE TO_CHAR(DATA_ADMISSAO, 'YYYY') >='2016';


/*Selecionando pessoas de férias que foram admitidas antes de 2016*/
SELECT * FROM TABELA_DE_VENDEDORES WHERE TO_CHAR(DATA_ADMISSAO, 'YYYY') < '2017' AND
DE_FERIAS = 1;
