/*RELATÓRIO DE VENDAS*/
/* VAMOS ANALISAR SE O VOLUMER DE VENDA FOI MAIOR OU MENOR DO QUE O ESPERADO*/
SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM'), INF.QUANTIDADE
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO;

SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM'), SUM(INF.QUANTIDADE)
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM');


SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM'), SUM(INF.QUANTIDADE)
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM');


SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;


SELECT CADASTRO.CPF, CADASTRO.NOME,VENDAS.MES_ANO, CADASTRO.VOLUME_DE_COMPRA,
VENDAS.VOLUME_VENDIDO FROM 
(SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM') AS MES_ANO, SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM')) VENDAS
INNER JOIN 
(SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES) CADASTRO
ON VENDAS.CPF = CADASTRO.CPF
WHERE MES_ANO = '2018-01';


SELECT CADASTRO.CPF, CADASTRO.NOME,VENDAS.MES_ANO, CADASTRO.VOLUME_DE_COMPRA,
VENDAS.VOLUME_VENDIDO,
CASE WHEN CADASTRO.VOLUME_DE_COMPRA <= VENDAS.VOLUME_VENDIDO THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS NÃO VÁLIDAS' END AS RESULTADO
FROM
(SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM') AS MES_ANO, SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM')) VENDAS
INNER JOIN 
(SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES) CADASTRO
ON VENDAS.CPF = CADASTRO.CPF
WHERE MES_ANO = '2018-01';

SELECT CADASTRO.CPF, CADASTRO.NOME,VENDAS.MES_ANO, CADASTRO.VOLUME_DE_COMPRA,
VENDAS.VOLUME_VENDIDO,'DIFERENÇA É '|| TO_CHAR(CADASTRO.VOLUME_DE_COMPRA - VENDAS.VOLUME_VENDIDO) AS DIFERENCA,
CASE WHEN CADASTRO.VOLUME_DE_COMPRA >= VENDAS.VOLUME_VENDIDO THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS NÃO VÁLIDAS' END AS RESULTADO
FROM
(SELECT NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM') AS MES_ANO, SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO
FROM NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA,'YYYY-MM')) VENDAS
INNER JOIN 
(SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES) CADASTRO
ON VENDAS.CPF = CADASTRO.CPF
WHERE CADASTRO.VOLUME_DE_COMPRA - VENDAS.VOLUME_VENDIDO < 0;

/*------------------------------------------------------------------------------------------------*/
/*RELATORIO 2: VOLUME DE VENDAS POR PRODUTO. QUAL PRODUTO VENDEU MAIS?*/

SELECT TP.SABOR, INF.QUANTIDADE FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO;

SELECT TP.SABOR, INF.QUANTIDADE , NF.DATA_VENDA FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON  NF.NUMERO = INF.NUMERO;

SELECT TP.SABOR, INF.QUANTIDADE ,TO_CHAR(NF.DATA_VENDA,'YYYY') FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON  NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY')=2016;


SELECT TP.SABOR, SUM(INF.QUANTIDADE) ,TO_CHAR(NF.DATA_VENDA,'YYYY') AS ANO FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON  NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY')=2016 
GROUP BY TP.SABOR,TO_CHAR(NF.DATA_VENDA,'YYYY');
/*QUERO AGORA MOSTRAR DO MAIOR PARA O MENOR*/

SELECT TP.SABOR, SUM(INF.QUANTIDADE) ,TO_CHAR(NF.DATA_VENDA,'YYYY') AS ANO FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON  NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY')=2016 
GROUP BY TP.SABOR,TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY SUM(INF.QUANTIDADE) DESC;


/*VAMOS BUSCAR AGORA O TOTAL DE VENDAS E FAZER UMA BUSCAR DA PORCENTAGEM*/
SELECT  SUM(INF.QUANTIDADE) ,TO_CHAR(NF.DATA_VENDA,'YYYY') AS ANO FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON  NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY')=2016 
GROUP BY TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY SUM(INF.QUANTIDADE) DESC;
/*3626240 É O TOTAL*/


SELECT TP.SABOR, SUM(INF.QUANTIDADE) ,TO_CHAR(NF.DATA_VENDA,'YYYY')AS ANO,ROUND(SUM(INF.QUANTIDADE)*100/3626240,2) AS PERCENTUAL
FROM ITENS_NOTAS_FISCAIS INF INNER JOIN
TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO =INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON  NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY')=2016 
GROUP BY TP.SABOR,TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY SUM(INF.QUANTIDADE) DESC;


/*FAZENDO POR TAMANHO*/
SELECT tp.tamanho,TO_CHAR(NF.DATA_VENDA,'YYYY'),INF.QUANTIDADE AS ANO FROM TABELA_DE_PRODUTOS TP INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO=inf.codigo_do_produto INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO;

SELECT tp.tamanho,TO_CHAR(NF.DATA_VENDA,'YYYY')AS ANO,SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM TABELA_DE_PRODUTOS TP INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO=inf.codigo_do_produto INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = '2016'
GROUP BY  TP.TAMANHO ,TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY (QUANTIDADE) DESC;

/*PEGANDO O TOTAL DE VENDAS*/
SELECT TO_CHAR(NF.DATA_VENDA,'YYYY')AS ANO,SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM TABELA_DE_PRODUTOS TP INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO=inf.codigo_do_produto INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = '2016'
GROUP BY TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY (QUANTIDADE) DESC;
/*3626240*/

SELECT tp.tamanho,TO_CHAR(NF.DATA_VENDA,'YYYY')AS ANO,SUM(INF.QUANTIDADE) AS QUANTIDADE,
ROUND(SUM(INF.QUANTIDADE)*100/3626240,2) AS PORCENTAGEM
FROM TABELA_DE_PRODUTOS TP INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO=inf.codigo_do_produto INNER JOIN NOTAS_FISCAIS NF
ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = '2016'
GROUP BY  TP.TAMANHO ,TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY (QUANTIDADE) DESC;

